paths:
  /sheets:
    get:
      summary: List available spreadsheets
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Optional case-insensitive name filter
      responses:
        '200':
          description: List of spreadsheets
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string

  /sheets/{id}/tabs:
    get:
      summary: List spreadsheet tabs
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: Spreadsheet ID
      responses:
        '200':
          description: List of tabs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    gid:
                      type: string
                    title:
                      type: string
        '404':
          description: Spreadsheet not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
